# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='miniarticle',
            options={'ordering': ['-pub_date'], 'verbose_name': '点滴', 'verbose_name_plural': '点滴'},
        ),
        migrations.AddField(
            model_name='articleimage',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='thumb_image', verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about_img', verbose_name='头像'),
        ),
    ]
